name: dataniverse_server
description: Dataniverse Server — banco de dados JSON acessível pela rede local.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  network_info_plus: ^6.1.4
  path: ^1.9.0
  path_provider: ^2.1.5
  http: ^1.2.1
  flutter_foreground_task: ^8.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true